### ISSUE TITLE
Serial.SerialPort is not a constructor

### ISSUE THREAD

**Issue by saramaebee** [Pecacheu/create2#1]
I just downloaded your api. I used your example `test.js`; however, I got this error:
```
TypeError: Serial.SerialPort is not a constructor
    at initSerial (C:\Users\saram\node_modules\create2\index.js:88:11)
    at Object.exports.open (C:\Users\saram\node_modules\create2\index.js:151:11)
    at C:\Users\saram\Desktop\iRobot\firstattempt.js:9:35
    at ReadStream.onPortSelectInput (C:\Users\saram\node_modules\create2\index.js:67:20)
    at emitOne (events.js:121:20)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at TTY.onread (net.js:594:20)```

**Comment by markwalt** [comment]
There are two errors in index.js. `new Serial.SerialPort` should read `new Serial` as below and `baudrate` should read `baudRate`. This fixed the issue for me and allowed me to connect.

```
serial = new Serial(port, {
  //Defaults for Roomba Open Interface:
  baudRate:115200, dataBits:8,
  parity:'none', stopBits:1,
  flowControl:false
});
```
